trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: haka-skia-variables
- name: version-full
  value: $(Major).$(Minor).$(Patch)

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(project)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: $(project)
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack private'
  inputs:
    command: 'pack'
    nobuild: true
    packagesToPack: '$(project)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    packDirectory: '$(Build.ArtifactStagingDirectory)/private'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack public'
  inputs:
    command: 'pack'
    nobuild: true
    packagesToPack: '$(project)'
    versioningScheme: byEnvVar
    versionEnvVar: version-full
    packDirectory: '$(Build.ArtifactStagingDirectory)/public'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
